https://b24-lmffg5.bitrix24.ua/workgroups/group/8/tasks/task/view/32/
romanivna/trron pull request #5
Opened 2019-08-28 08:05 UTC by SaldanRoman

2019-08-28 09:05 UTC, maradroman commented on index.html
> +	 <div class="main-slider">
class name is not in BEM methodology. expected "slider-main"

2019-08-28 09:10 UTC, maradroman commented on css/slider.css
> +
unnecessary space

2019-08-28 09:10 UTC, maradroman commented on css/slider.css
> +
unnecessary space

2019-08-28 09:11 UTC, maradroman commented on css/slider.css
> +
unnecessary space

2019-08-28 09:11 UTC, maradroman commented on css/slider.css
> +
unnecessary space

2019-08-28 09:11 UTC, maradroman commented on css/slider.css
> +
unnecessary space

2019-08-28 09:11 UTC, maradroman commented on css/slider.css
> +
unnecessary space

2019-08-28 09:14 UTC, maradroman commented on css/slider.css
> +    background-color: rgb(252, 165, 60);
hex code expected, #fca53c

2019-08-28 09:21 UTC, maradroman reviewed
commented mistakes, please fix

2019-08-28 18:52 UTC, romanivna commented on css/slider.css
> +    transition: 300ms;
.3s (leading zero is deprecated)

2019-08-28 18:52 UTC, romanivna commented on css/slider.css
> +    transition: 300ms;
.3s

2019-08-28 18:53 UTC, romanivna commented on css/slider.css
> +    opacity: 0.5;
.5

2019-08-28 18:59 UTC, OlecsandrStelmakh submitted a review, later dismissed

2019-08-28 19:00 UTC, maradroman commented on css/slider.css
> +    background-color: lightgrey;
hex code expected, #d3d3d3

2019-08-28 19:11 UTC, maradroman commented on css/slider.css
> +    transition: 600ms;
.6s

2019-08-28 19:46 UTC, maradroman commented on js/slider.js
> +    let timeCount = 50;
redundant variable (unused)

2019-08-30 17:22 UTC, OlecsandrStelmakh approved these changes

2019-08-30 17:54 UTC, OlecsandrStelmakh submitted a review, later dismissed

2019-08-30 18:10 UTC, romanivna commented on js/slider.js
> +    let timeCount = 50;
remove unnecessary variable

2019-08-30 18:30 UTC, SaldanRoman commented on js/slider.js
> +    let timeCount = 50;
done !)

2019-08-30 18:41 UTC, romanivna commented on index.html
> +	 <div class="slider-main">
slider

2019-08-30 18:42 UTC, romanivna commented on index.html
> +            <div class="slider-item-buttons left">
slider-button slider-button--left

2019-08-30 18:45 UTC, romanivna commented on index.html
> +                <button onclick="sliderPrevious()" id="mainSliderButtonLeft">&#10094</button>
slider-button

2019-08-30 18:46 UTC, romanivna commented on index.html
> +            <div class="slider-item-container"></div>
slider-container

2019-08-30 18:47 UTC, romanivna commented on index.html
> +            <div class="slider-item-container"></div>
> slider-container-item
      > slider-container-item-text
             >slider-container-item-text-title

2019-08-30 18:48 UTC, romanivna commented on css/slider.css
> +.slider-item-buttons button{
.slider-button

2019-08-30 18:48 UTC, romanivna commented on js/slider.js
> +const arrayOfSliderProd = [{
move to json

2019-08-30 18:49 UTC, romanivna commented on js/slider.js
> +const arrayOfSliderProd = [{
translate to english

2019-08-30 18:50 UTC, romanivna commented on js/slider.js
> +function generatediv(ppclass, index, obj) {
generateSlide / Block / sliderBlock / sliderElement

2019-08-30 18:51 UTC, romanivna commented on js/slider.js
> +function generatediv(ppclass, index, obj) {
generateAndAddToHtmlSlideBlock

2019-08-30 18:51 UTC, romanivna commented on js/slider.js
> +function generatediv(ppclass, index, obj) {
ppclass????

2019-08-30 18:52 UTC, romanivna commented on js/slider.js
> +function generatediv(ppclass, index, obj) {
index > currentSlideIndex

2019-08-30 18:53 UTC, romanivna commented on js/slider.js
> +function generatediv(ppclass, index, obj) {
obj => slideDataObj

2019-08-30 18:55 UTC, romanivna commented on js/slider.js
> +    const sliderItem = document.createElement('div');
wrapper

2019-08-30 18:55 UTC, romanivna commented on js/slider.js
> +    const sliderItemContent = document.createElement('div');
textWrapper

2019-08-30 18:55 UTC, romanivna commented on js/slider.js
> +    const sliderItemContentTextTitle = document.createElement('p');
title

2019-08-30 18:56 UTC, romanivna commented on js/slider.js
> +    sliderItemContentButton.innerText = 'ПОПРОБОВАТЬ';
translate

2019-08-30 18:57 UTC, romanivna commented on js/slider.js
> +    window.sliderContainer = document.querySelector('.slider-item-container');
fetch().then( () => geberatekhgkhkg)

2019-08-30 18:58 UTC, romanivna commented on js/slider.js
> +    sliderContainer.appendChild(generatediv('left', 3, arrayOfSliderProd[3]));
last index of array

2019-08-30 18:59 UTC, romanivna commented on js/slider.js
> +    sliderContainer.appendChild(generatediv('left', 3, arrayOfSliderProd[3]));
const lastIndex = arrayOfSliderProd.length - 1;

2019-08-30 19:01 UTC, romanivna commented on js/slider.js
> +    let timeCount = 50;
rename

2019-08-30 19:01 UTC, romanivna commented on js/slider.js
> +    const itemTextArr = document.querySelectorAll('.slider-item-content p, .slider-item-content a');
.slider-item-content-text-subtitle
not a => set it a class

2019-08-30 19:03 UTC, romanivna commented on js/slider.js
> +(function() {
move to end

2019-08-30 19:04 UTC, romanivna commented on js/slider.js
> +document.querySelector('#mainSliderButtonLeft').addEventListener('click', function() {
getElementById

2019-08-30 19:05 UTC, romanivna commented on js/slider.js
> +    clearInterval(mainsliderInterval);
146 and 147 strings -> move to function

2019-08-30 19:05 UTC, romanivna commented on js/slider.js
> +    clearInterval(mainsliderInterval);
resetInterval()

2019-08-30 19:08 UTC, romanivna commented on js/slider.js
> +    clearInterval(mainsliderInterval);
clickToButton(position) {
if (position === 'left') { sliderPrevious() }
else sliderNext()
resetInterval()
}

2019-08-30 19:08 UTC, romanivna commented on index.html
> +                <button onclick="sliderNext()" id="mainSliderButtonRight">&#10095</button>
onclick=clickToButton('left' || 'right')

2019-09-01 19:08 UTC, romanivna commented on css/slider.css
> +.slider-main{
add Prettier plugin for your IDE and create hotkey for it. use it every time when you save the file.
between selector and brace should be space.

2019-09-01 19:09 UTC, romanivna commented on css/slider.css
> +.slider-item-buttons button:hover{
set button his own class and use it instead of this construnction

2019-09-01 19:09 UTC, romanivna commented on css/slider.css
> +    color: #ffffff;
use short hex names (fff instead of ffffff)

2019-09-01 19:10 UTC, romanivna commented on css/slider.css
> +    text-shadow: 0px 0px 1px black;
when value is 0 - where couldn't be any measurements. 0% and 0px it's a zero.
so don't write measure.
use just "0"

2019-09-01 19:10 UTC, romanivna commented on css/slider.css
> +    margin: 4% 10% 0% 0%;
same, just 0
look throw all css and remove measures after 0

2019-09-03 17:57 UTC, OlecsandrStelmakh commented on js/slider.js
> +function changSlide(direction){
space before brackets

2019-09-03 17:58 UTC, OlecsandrStelmakh commented on js/slider.js
> +    }else{
space before brackets

2019-09-03 17:58 UTC, OlecsandrStelmakh submitted a review, later dismissed

2019-09-03 18:23 UTC, romanivna commented on css/slider.css
> +.slider-content--left{
SPACES!!!!!

2019-09-03 18:24 UTC, romanivna commented on js/slider.js
> +fetch('./jsons/slider.json').then(respons => respons.json()).then(data => {arrayOfSliderProd = data; createSlider(); changSlide()});
response

2019-09-03 18:24 UTC, romanivna commented on js/slider.js
> +fetch('./jsons/slider.json').then(respons => respons.json()).then(data => {arrayOfSliderProd = data; createSlider(); changSlide()});
and please makeeach step on separate line.add prettier.

2019-09-03 18:26 UTC, romanivna commented on js/slider.js
> +fetch('./jsons/slider.json').then(respons => respons.json()).then(data => {arrayOfSliderProd = data; createSlider(); changSlide()});
when you call function - this function should be close as soon as possible to place where it called.

2019-09-03 18:26 UTC, romanivna commented on js/slider.js
> +    slider.appendChild(generateSlide('slider-content--left', arrayOfSliderProd.length-1, arrayOfSliderProd[arrayOfSliderProd.length-1]));
arrayOfSliderProd.length-1 move to variable

2019-09-03 18:27 UTC, romanivna commented on js/slider.js
> +    let timeoutValue= 50;
rename

2019-09-03 18:43 UTC, romanivna commented on js/slider.js
> +fetch('./jsons/slider.json').then(respons => respons.json()).then(data => {arrayOfSliderProd = data; createSlider(); changSlide()});
`fetch('./jsons/slider.json')
  .then(respons => respons.json())
  .then(data => {
     arrayOfSliderProd = data;
     createSlider(); 
     changSlide()
});`

2019-09-03 19:05 UTC, maradroman submitted a review, later dismissed

2019-09-04 18:08 UTC, OlecsandrStelmakh submitted a review, later dismissed

2019-09-06 06:22 UTC, OlecsandrStelmakh approved these changes

2019-09-06 06:30 UTC, romanivna submitted a review, later dismissed

2019-09-06 06:40 UTC, OlecsandrStelmakh requested changes
on the phone version the problem with the pictures (invisible bottles), and in general it was not bad that the text appeared more slowly

2019-09-06 08:01 UTC, OlecsandrStelmakh submitted a review, later dismissed

2019-09-07 07:55 UTC, OlecsandrStelmakh submitted a review, later dismissed

2019-09-07 13:32 UTC, romanivna commented on css/slider.css
> +  left: 0.5%;
.5s
make settings or prettier with this rule or add sass-lint also

2019-09-07 13:33 UTC, romanivna submitted a review, later dismissed

2019-09-07 13:35 UTC, romanivna commented on styles.css
> +
we don't need empty lines between imports.
empty line should be after all imports before file content
remove please

2019-09-08 19:24 UTC, romanivna approved these changes

2019-09-08 19:25 UTC, merged